version: '3'

services:
  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server
    restart: always
    ports:
      - "9090:9090"

    volumes:
      - type: bind
        source: eureka-server
        target: /app

  machine-microservice:
    build:
      context: .
      dockerfile: machine-microservice/Dockerfile
    container_name: machine-microservice
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - machines-database
    volumes:
      - type: bind
        source: machine-microservice
        target: /app

  customer-microservice:
    build:
      context: .
      dockerfile: customer-microservice/Dockerfile
    container_name: customer-microservice
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - customers-database
    volumes:
      - type: bind
        source: customer-microservice
        target: /app

  machines-database:
    container_name: machines-database
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5532:5532'
    environment:
      POSTGRES_DB: machines-database
      POSTGRES_USER: machines
      POSTGRES_PASSWORD: 1234
      PGPORT: 5532
    volumes:
      - ./databases/machines-data:/var/lib/postgresql/data
      
  customers-database:
    container_name: customers-database
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5533:5533'
    environment:
      POSTGRES_DB: customers-database
      POSTGRES_USER: customers
      POSTGRES_PASSWORD: 1234
      PGPORT: 5533
    volumes:
      - ./databases/customers-database:/var/lib/postgresql/data