location:
   eureka: eureka-server:9090
 
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${location.eureka}/eureka
    registerWithEureka: true
    fetchRegistry: true
   
